name: BukkitKart
author: ThePlaceholderTeam
main: net.theplaceholderteam.bukkitkart.BukkitKart
version: 0.1a
commands:
    bukkitkart:
        description: BukkitKart universal command.
        usage: /bukkitkart help